# Generated by Django 3.2.25 on 2024-05-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_marketingsubscription_discount_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingSubscription',
        ),
    ]
