# Generated by Django 3.2.25 on 2024-03-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_multibuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='clearance',
        ),
    ]
