# Generated by Django 3.2.25 on 2024-04-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='multibuy',
        ),
    ]
