# Generated by Django 3.2.25 on 2024-05-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_multibuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clearance',
        ),
    ]
